CREATE TABLE schools (
  id INT AUTO_INCREMENT PRIMARY KEY,
  codice_mecc VARCHAR(12) UNIQUE,
  denominazione VARCHAR(255),
  regione VARCHAR(100),
  provincia VARCHAR(100),
  comune VARCHAR(100),
  sito_web VARCHAR(255),
  tipologia VARCHAR(100),
  indirizzo VARCHAR(255),
  cap VARCHAR(5),
  email VARCHAR(100),
  pec VARCHAR(100),
  codice_istituto_riferimento VARCHAR(12),
  denominazione_istituto_riferimento VARCHAR(255),
  area_geografica VARCHAR(50),
  caratteristica_scuola VARCHAR(100),
  sede_direttivo ENUM('SI', 'NO') DEFAULT 'NO',
  sede_omnicomprensivo VARCHAR(50),
  sede_scolastica ENUM('SI', 'NO') DEFAULT 'NO',
  anno_scolastico VARCHAR(10),
  codice_comune VARCHAR(10),
  stato_crawler ENUM('attivo', 'inattivo', 'errore') DEFAULT 'inattivo',
  ultima_scansione DATETIME DEFAULT NULL,
  numero_scansioni INT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  
  INDEX idx_regione (regione),
  INDEX idx_provincia (provincia),
  INDEX idx_comune (comune),
  INDEX idx_tipologia (tipologia),
  INDEX idx_area_geografica (area_geografica),
  INDEX idx_istituto_riferimento (codice_istituto_riferimento)
);

CREATE TABLE tenders (
  id INT AUTO_INCREMENT PRIMARY KEY,
  school_id INT,
  title VARCHAR(500),
  type VARCHAR(100),
  deadline DATE,
  publish_date DATE,
  url TEXT,
  summary TEXT,
  last_checked DATETIME,
  UNIQUE key_uni (school_id, url(255)),
  FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE
);
